// Code generated by mockery v2.46.3. DO NOT EDIT.

package unit_of_work

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUnitOfWork is an autogenerated mock type for the UnitOfWork type
type MockUnitOfWork[T any] struct {
	mock.Mock
}

type MockUnitOfWork_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockUnitOfWork[T]) EXPECT() *MockUnitOfWork_Expecter[T] {
	return &MockUnitOfWork_Expecter[T]{mock: &_m.Mock}
}

// Commit provides a mock function with given fields: ctx
func (_m *MockUnitOfWork[T]) Commit(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUnitOfWork_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockUnitOfWork_Commit_Call[T any] struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUnitOfWork_Expecter[T]) Commit(ctx interface{}) *MockUnitOfWork_Commit_Call[T] {
	return &MockUnitOfWork_Commit_Call[T]{Call: _e.mock.On("Commit", ctx)}
}

func (_c *MockUnitOfWork_Commit_Call[T]) Run(run func(ctx context.Context)) *MockUnitOfWork_Commit_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUnitOfWork_Commit_Call[T]) Return(_a0 error) *MockUnitOfWork_Commit_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUnitOfWork_Commit_Call[T]) RunAndReturn(run func(context.Context) error) *MockUnitOfWork_Commit_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function with given fields: ctx
func (_m *MockUnitOfWork[T]) Rollback(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUnitOfWork_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockUnitOfWork_Rollback_Call[T any] struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUnitOfWork_Expecter[T]) Rollback(ctx interface{}) *MockUnitOfWork_Rollback_Call[T] {
	return &MockUnitOfWork_Rollback_Call[T]{Call: _e.mock.On("Rollback", ctx)}
}

func (_c *MockUnitOfWork_Rollback_Call[T]) Run(run func(ctx context.Context)) *MockUnitOfWork_Rollback_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUnitOfWork_Rollback_Call[T]) Return(_a0 error) *MockUnitOfWork_Rollback_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUnitOfWork_Rollback_Call[T]) RunAndReturn(run func(context.Context) error) *MockUnitOfWork_Rollback_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Tx provides a mock function with given fields:
func (_m *MockUnitOfWork[T]) Tx() T {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Tx")
	}

	var r0 T
	if rf, ok := ret.Get(0).(func() T); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(T)
	}

	return r0
}

// MockUnitOfWork_Tx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tx'
type MockUnitOfWork_Tx_Call[T any] struct {
	*mock.Call
}

// Tx is a helper method to define mock.On call
func (_e *MockUnitOfWork_Expecter[T]) Tx() *MockUnitOfWork_Tx_Call[T] {
	return &MockUnitOfWork_Tx_Call[T]{Call: _e.mock.On("Tx")}
}

func (_c *MockUnitOfWork_Tx_Call[T]) Run(run func()) *MockUnitOfWork_Tx_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnitOfWork_Tx_Call[T]) Return(_a0 T) *MockUnitOfWork_Tx_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUnitOfWork_Tx_Call[T]) RunAndReturn(run func() T) *MockUnitOfWork_Tx_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockUnitOfWork creates a new instance of MockUnitOfWork. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnitOfWork[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnitOfWork[T] {
	mock := &MockUnitOfWork[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
